name: linting

on: [push, pull_request]

jobs:
  lint-md:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v17
      with:
        globs: |
          *.md
  lint-html:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: ./
